DROP TABLE IF EXISTS post;
CREATE TABLE post (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  body VARCHAR(255)  NOT NULL,
  visible BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL
);

DROP TABLE IF EXISTS account;
CREATE TABLE account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    token VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS packing_list_item;
CREATE TABLE packing_list_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    ticked_off BOOLEAN NOT NULL DEFAULT FALSE,
    person_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL
);